In [ ]:
#download the numpy through cmd 
# command : pip install numpy
# the import it

In [1]:

import numpy as np


In [2]:
array=np.arange(8)


In [3]:
array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
array.shape
#as  we see the (1,8)and (8,) same 


(8,)

In [5]:
array.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#by the list and tuples to make the numpy array

In [6]:
lis=np.array([0,1,2,3,4,5,6,7])#creating array 

In [7]:
lis

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
lis.reshape(2,4)#it reshape the  original shape to 2*4 matrix shape

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#as we show the list method and the numpy method is same 

In [11]:
lis.ravel()#ravel make the shape to the original 

array([0, 1, 2, 3, 4, 5, 6, 7])

#Diving into Acessing the value from the numpy array

In [14]:
arr=np.arange(10,50,5)# (start_value,end_value,step)

# aranging the number from 10 to 49 with the step of 5


In [15]:
arr

array([10, 15, 20, 25, 30, 35, 40, 45])

#Creating the identity matrix using eye method

In [16]:
ar=np.eye(3)#3 means 3*3matrix


In [17]:
ar


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Using full method to fill same value to the dedicated shape matrix

In [20]:
ar_full=np.full((4,5),fill_value=7)

In [21]:
ar_full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

#Creating linspace between 0 to 100 having 8 digits

In [22]:
ar_lin=np.linspace(0,100,8)

In [23]:
ar_lin

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])